/*
-- Query: select * from Appointment_Details
LIMIT 0, 1000

-- Date: 2023-03-25 15:18
*/
INSERT INTO `` (`appid`,`age`,`app_date`,`app_time`,`app_time_statue`,`blood_group`,`bp`,`city`,`contact`,`doctorid`,`doctor_name`,`fees`,`height`,`meeting_type`,`patient_name`,`sugar`,`userid`,`weight`,`patient_type`) VALUES (1,NULL,NULL,'09:00 AM','Free',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `` (`appid`,`age`,`app_date`,`app_time`,`app_time_statue`,`blood_group`,`bp`,`city`,`contact`,`doctorid`,`doctor_name`,`fees`,`height`,`meeting_type`,`patient_name`,`sugar`,`userid`,`weight`,`patient_type`) VALUES (2,NULL,NULL,'09:30 AM','Free',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `` (`appid`,`age`,`app_date`,`app_time`,`app_time_statue`,`blood_group`,`bp`,`city`,`contact`,`doctorid`,`doctor_name`,`fees`,`height`,`meeting_type`,`patient_name`,`sugar`,`userid`,`weight`,`patient_type`) VALUES (3,NULL,NULL,'10:00 AM','Free',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `` (`appid`,`age`,`app_date`,`app_time`,`app_time_statue`,`blood_group`,`bp`,`city`,`contact`,`doctorid`,`doctor_name`,`fees`,`height`,`meeting_type`,`patient_name`,`sugar`,`userid`,`weight`,`patient_type`) VALUES (4,NULL,NULL,'10:30 AM','free',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `` (`appid`,`age`,`app_date`,`app_time`,`app_time_statue`,`blood_group`,`bp`,`city`,`contact`,`doctorid`,`doctor_name`,`fees`,`height`,`meeting_type`,`patient_name`,`sugar`,`userid`,`weight`,`patient_type`) VALUES (5,NULL,NULL,'11:00 AM','free',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `` (`appid`,`age`,`app_date`,`app_time`,`app_time_statue`,`blood_group`,`bp`,`city`,`contact`,`doctorid`,`doctor_name`,`fees`,`height`,`meeting_type`,`patient_name`,`sugar`,`userid`,`weight`,`patient_type`) VALUES (6,NULL,NULL,'11:30 AM','free',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `` (`appid`,`age`,`app_date`,`app_time`,`app_time_statue`,`blood_group`,`bp`,`city`,`contact`,`doctorid`,`doctor_name`,`fees`,`height`,`meeting_type`,`patient_name`,`sugar`,`userid`,`weight`,`patient_type`) VALUES (7,NULL,NULL,'12:00 PM','Free',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `` (`appid`,`age`,`app_date`,`app_time`,`app_time_statue`,`blood_group`,`bp`,`city`,`contact`,`doctorid`,`doctor_name`,`fees`,`height`,`meeting_type`,`patient_name`,`sugar`,`userid`,`weight`,`patient_type`) VALUES (8,NULL,NULL,'12:30 PM','free',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `` (`appid`,`age`,`app_date`,`app_time`,`app_time_statue`,`blood_group`,`bp`,`city`,`contact`,`doctorid`,`doctor_name`,`fees`,`height`,`meeting_type`,`patient_name`,`sugar`,`userid`,`weight`,`patient_type`) VALUES (9,NULL,NULL,'01:00 PM','free',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `` (`appid`,`age`,`app_date`,`app_time`,`app_time_statue`,`blood_group`,`bp`,`city`,`contact`,`doctorid`,`doctor_name`,`fees`,`height`,`meeting_type`,`patient_name`,`sugar`,`userid`,`weight`,`patient_type`) VALUES (10,NULL,NULL,'01:30 PM','free',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `` (`appid`,`age`,`app_date`,`app_time`,`app_time_statue`,`blood_group`,`bp`,`city`,`contact`,`doctorid`,`doctor_name`,`fees`,`height`,`meeting_type`,`patient_name`,`sugar`,`userid`,`weight`,`patient_type`) VALUES (11,NULL,NULL,'02:00 PM','free',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `` (`appid`,`age`,`app_date`,`app_time`,`app_time_statue`,`blood_group`,`bp`,`city`,`contact`,`doctorid`,`doctor_name`,`fees`,`height`,`meeting_type`,`patient_name`,`sugar`,`userid`,`weight`,`patient_type`) VALUES (12,NULL,NULL,'02:30 PM','free',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `` (`appid`,`age`,`app_date`,`app_time`,`app_time_statue`,`blood_group`,`bp`,`city`,`contact`,`doctorid`,`doctor_name`,`fees`,`height`,`meeting_type`,`patient_name`,`sugar`,`userid`,`weight`,`patient_type`) VALUES (13,NULL,NULL,'03:00 PM','free',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `` (`appid`,`age`,`app_date`,`app_time`,`app_time_statue`,`blood_group`,`bp`,`city`,`contact`,`doctorid`,`doctor_name`,`fees`,`height`,`meeting_type`,`patient_name`,`sugar`,`userid`,`weight`,`patient_type`) VALUES (14,NULL,NULL,'03:30 PM','free',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `` (`appid`,`age`,`app_date`,`app_time`,`app_time_statue`,`blood_group`,`bp`,`city`,`contact`,`doctorid`,`doctor_name`,`fees`,`height`,`meeting_type`,`patient_name`,`sugar`,`userid`,`weight`,`patient_type`) VALUES (15,NULL,NULL,'04:00 PM','free',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `` (`appid`,`age`,`app_date`,`app_time`,`app_time_statue`,`blood_group`,`bp`,`city`,`contact`,`doctorid`,`doctor_name`,`fees`,`height`,`meeting_type`,`patient_name`,`sugar`,`userid`,`weight`,`patient_type`) VALUES (16,NULL,NULL,'04:30 PM','free',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `` (`appid`,`age`,`app_date`,`app_time`,`app_time_statue`,`blood_group`,`bp`,`city`,`contact`,`doctorid`,`doctor_name`,`fees`,`height`,`meeting_type`,`patient_name`,`sugar`,`userid`,`weight`,`patient_type`) VALUES (17,NULL,NULL,'05:00 PM','free',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `` (`appid`,`age`,`app_date`,`app_time`,`app_time_statue`,`blood_group`,`bp`,`city`,`contact`,`doctorid`,`doctor_name`,`fees`,`height`,`meeting_type`,`patient_name`,`sugar`,`userid`,`weight`,`patient_type`) VALUES (18,NULL,NULL,'05:30 PM','free',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `` (`appid`,`age`,`app_date`,`app_time`,`app_time_statue`,`blood_group`,`bp`,`city`,`contact`,`doctorid`,`doctor_name`,`fees`,`height`,`meeting_type`,`patient_name`,`sugar`,`userid`,`weight`,`patient_type`) VALUES (19,NULL,NULL,'06:00 PM','free',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `` (`appid`,`age`,`app_date`,`app_time`,`app_time_statue`,`blood_group`,`bp`,`city`,`contact`,`doctorid`,`doctor_name`,`fees`,`height`,`meeting_type`,`patient_name`,`sugar`,`userid`,`weight`,`patient_type`) VALUES (20,NULL,NULL,'06:30 PM','free',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `` (`appid`,`age`,`app_date`,`app_time`,`app_time_statue`,`blood_group`,`bp`,`city`,`contact`,`doctorid`,`doctor_name`,`fees`,`height`,`meeting_type`,`patient_name`,`sugar`,`userid`,`weight`,`patient_type`) VALUES (21,NULL,NULL,'07:00 PM','free',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `` (`appid`,`age`,`app_date`,`app_time`,`app_time_statue`,`blood_group`,`bp`,`city`,`contact`,`doctorid`,`doctor_name`,`fees`,`height`,`meeting_type`,`patient_name`,`sugar`,`userid`,`weight`,`patient_type`) VALUES (22,NULL,NULL,'07:30 PM','free',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `` (`appid`,`age`,`app_date`,`app_time`,`app_time_statue`,`blood_group`,`bp`,`city`,`contact`,`doctorid`,`doctor_name`,`fees`,`height`,`meeting_type`,`patient_name`,`sugar`,`userid`,`weight`,`patient_type`) VALUES (23,NULL,NULL,'08:00 PM','free',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `` (`appid`,`age`,`app_date`,`app_time`,`app_time_statue`,`blood_group`,`bp`,`city`,`contact`,`doctorid`,`doctor_name`,`fees`,`height`,`meeting_type`,`patient_name`,`sugar`,`userid`,`weight`,`patient_type`) VALUES (24,NULL,NULL,'08:30 PM','free',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `` (`appid`,`age`,`app_date`,`app_time`,`app_time_statue`,`blood_group`,`bp`,`city`,`contact`,`doctorid`,`doctor_name`,`fees`,`height`,`meeting_type`,`patient_name`,`sugar`,`userid`,`weight`,`patient_type`) VALUES (25,NULL,NULL,'09:00 PM','free',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
